insert into public.government_schemes
(name,description,benefit,eligibility,documents,application_steps,official_url,last_updated)
values
('PM-KISAN', 'Income support for eligible landholding farmer families through direct benefit transfer.', 'Up to ₹6,000 per year, paid in three instalments of ₹2,000.', 'Eligible landholding farmer families, subject to government exclusions and verification.', 'Aadhaar; mobile number; bank account details; land records', '["Open the official PM-KISAN portal","Choose New Farmer Registration","Verify Aadhaar and enter land and bank details","Submit and save the registration number"]'::jsonb, 'https://pmkisan.gov.in/', current_date),
('Pradhan Mantri Fasal Bima Yojana', 'Crop insurance protection against notified natural risks, pests and diseases.', 'Financial support for eligible crop losses; premium rates and coverage depend on the notified crop and season.', 'Farmers growing notified crops in notified areas, including sharecroppers and tenant farmers where applicable.', 'Aadhaar; land or tenancy proof; bank details; sowing declaration', '["Open the official PMFBY portal","Select your state, season and crop","Review the notified premium and coverage","Apply through the available insurer, bank or CSC channel"]'::jsonb, 'https://pmfby.gov.in/', current_date),
('Kisan Credit Card', 'Flexible short-term credit for cultivation, post-harvest needs and allied agricultural activities.', 'Access timely agricultural credit; interest support and limits depend on eligibility, bank rules and government directions.', 'Farmers, tenant farmers, sharecroppers, self-help groups and joint liability groups involved in farming or allied activities.', 'Identity and address proof; land or cultivation proof; photographs; bank-required documents', '["Open the official scheme information page","Check eligibility and required documents","Apply through a participating bank branch or its digital channel","Complete bank verification and credit assessment"]'::jsonb, 'https://www.myscheme.gov.in/schemes/kcc', current_date),
('Soil Health Card', 'Soil testing and nutrient recommendations to help farmers use fertiliser more efficiently.', 'A soil health report with nutrient status and crop-specific fertiliser recommendations.', 'Farmers can use the government soil testing service as available through their state or district centre.', 'Farmer details; land or plot information; soil sample as instructed by the centre', '["Open the Soil Health portal","Find a nearby soil testing centre or service","Submit the soil sample and plot details","Collect the report and follow the recommended dosage"]'::jsonb, 'https://soilhealth.dac.gov.in/', current_date),
('PM-KUSUM', 'Support for solar pumps and decentralised solar energy for farmers, subject to state implementation.', 'Subsidy or financial support for eligible solar pumps and renewable energy installations; amount varies by component and state.', 'Eligibility, component availability and application windows are determined by the state implementing agency.', 'Aadhaar; land ownership or cultivation proof; bank details; electricity or pump documents where required', '["Open the official PM-KUSUM portal","Check your state implementing agency and active component","Review subsidy, contribution and vendor details","Apply through the state portal or authorised agency"]'::jsonb, 'https://pmkusum.mnre.gov.in/', current_date)
on conflict do nothing;
